# -*- coding: utf-8 -*-
"""Copy of dataprep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1G3btdsFr2wib1sISZMmdAyEZz7BAsPag
"""

import pandas as pd
import numpy as np
import re
import random
from collections import defaultdict, Counter
from itertools import combinations
from sklearn.preprocessing import StandardScaler
from torch.utils.data import Dataset
import torch
from torch_geometric.loader import NeighborLoader
from torch_geometric.data import HeteroData
import networkx as nx
from torch.utils.data import Dataset, DataLoader

#Convert features

#convert sp
def convert_sp(x):
    if pd.isna(x) or x == '':
        return None

    x = x.replace('F', '').replace('J', '').replace('C', '')

    if x == 'Evens' or x == "Evs":
        return 1.0

    if '/' in x:
        num, den = x.split('/')
        return float(num) / float(den)

    try:
        return float(x)
    except:
        return None


#convert distance to furlongs
def convert_dist(x):
  if pd.isna(x):
        return None

  x = str(x).strip()

  miles = re.search(r'(\d+)m', x)
  furlongs = re.search(r'(\d+(?:/\d+)?)f', x)

  total = 0

  if miles:
      total += int(miles.group(1)) * 8

  if furlongs:
      f = furlongs.group(1)
      if '/' in f:
          num, den = f.split('/')
          total += float(num) / float(den)
      else:
          total += float(f)

  return total

#cleaning names
def clean_horses_names(name):
    if pd.isna(name):
        return None

    name = re.sub(r'[()]', '', name)
    name = name.lower().strip()
    name = re.sub(r'\.', '', name)
    name = re.sub(r'\b(i)\b', '', name)
    name = re.sub(r'\s+', ' ', name).strip()

    return name

def clean_names(name):
  if pd.isna(name):
        return None

  name = name.lower().strip()
  name = re.sub(r"\b(mr|mrs|ms|miss|dr)\b", "", name)
  name = name.replace("'", "")
  name = re.sub(r"[^a-z\s]", " ", name)
  name = " ".join(name.split())

  return name

#Identify where trainers and oweners are referenced by multiple names

# Remove titles from names
def strip_titles(name):

    titles = {"mr", "mrs", "ms", "miss"}

    return [
        x.lower()
        for x in name.split()
        if x.lower() not in titles
    ]

# Match two cleaned names

def matches_name(base_parts, candidate_parts):

    # surname
    if base_parts[-1] != candidate_parts[-1]:
        return False


    # first name
    base_first = base_parts[0]
    candidate_first = candidate_parts[0]


    if len(base_first) == 1:

        if candidate_first[0] != base_first:
            return False

    else:

        if candidate_first != base_first:
            return False



    # middle names

    base_middle = base_parts[1:-1]
    candidate_middle = candidate_parts[1:-1]


    for i, middle in enumerate(base_middle):

        if i >= len(candidate_middle):
            return False


        if len(middle) == 1:

            if candidate_middle[i][0] != middle:
                return False

        else:

            if candidate_middle[i] != middle:
                return False


    return True

# Check whether candidates are genuinely conflicting identities

def candidate_group_conflict(candidates):

    cleaned = [
        strip_titles(name)
        for name in candidates
    ]


    for i in range(len(cleaned)):

        for j in range(i + 1, len(cleaned)):

            a = cleaned[i]
            b = cleaned[j]


            # surname
            if a[-1] != b[-1]:
                return True


            # first name
            if (
                len(a[0]) > 1
                and len(b[0]) > 1
                and a[0] != b[0]
            ):
                return True


            # middle names

            middle_a = a[1:-1]
            middle_b = b[1:-1]


            if middle_a and middle_b:

                if len(middle_a) != len(middle_b):
                    return True


                for x, y in zip(middle_a, middle_b):

                    if len(x) > 1 and len(y) > 1:

                        if x != y:
                            return True


                    elif len(x) == 1 and len(y) > 1:

                        if x != y[0]:
                            return True


                    elif len(y) == 1 and len(x) > 1:

                        if y != x[0]:
                            return True


    return False

def match_table(entity, df):

  entity_clean = f"{entity}_clean"

  # Store original names for display

  entity_display = (
      df[[entity_clean, entity]]
      .dropna()
      .drop_duplicates()
      .groupby(entity_clean)[entity]
      .apply(list)
      .to_dict()
  )

  # Unique cleaned names

  entity_names = pd.DataFrame({
      entity_clean: df[entity_clean]
      .dropna()
      .unique()
  })


  entity_names["parts"] = (
      entity_names[entity_clean]
      .str.split()
  )


  entity_names = entity_names[
      entity_names["parts"].str.len() >= 2
  ].copy()


  entity_names["surname"] = (
      entity_names["parts"]
      .str[-1]
  )

  # Group by surname

  surname_groups = defaultdict(list)


  for row in entity_names.itertuples(index=False):

      surname_groups[row.surname].append(
          (
              getattr(row, entity_clean),
              row.parts
          )
      )

  # Find possible matches

  results = []


  for row in entity_names.itertuples(index=False):

      base_name = getattr(row, entity_clean)
      base_parts = row.parts
      surname = row.surname


      candidates = []


      for candidate_name, candidate_parts in surname_groups[surname]:

          if candidate_name == base_name:
              continue

          if matches_name(base_parts, candidate_parts):
              candidates.append(candidate_name)



      candidates = sorted(set(candidates))

      # Keep only genuine conflicts

      if (
          len(candidates) >= 2
          and candidate_group_conflict(candidates)
      ):


          base_display = entity_display.get(
              base_name,
              [base_name]
          )


          candidate_display = []

          for candidate in candidates:

              candidate_display.extend(
                  entity_display.get(
                      candidate,
                      [candidate]
                  )
              )

          candidate_display = sorted(
              set(candidate_display)
          )

          results.append({
              "base_name": ", ".join(base_display),
              "n_candidates": len(candidate_display),
              "candidates": ", ".join(candidate_display)

          })

  # Initial ambiguity table

  final_match_table = pd.DataFrame(results)
  return final_match_table

def overlap(entity, final_match_table, df):

  entity_clean = f"{entity}_clean"

  entity_original_to_clean = (
      df[[entity, entity_clean]]
      .dropna()
      .drop_duplicates()
      .set_index(entity)[entity_clean]
      .to_dict()
  )


  # entity_clean to horse_clean set

  entity_horses = (
      df.dropna(subset=[entity_clean, "horse_id"])
        .groupby(entity_clean)["horse_id"]
        .apply(set)
        .to_dict()
  )

  # entity name to horses

  def entity_to_horses(name):

      clean_name = entity_original_to_clean.get(name)

      if clean_name is None:
          return set()

      return entity_horses.get(clean_name, set())

  # Find overlaps

  def find_overlap_pairs(row):

      base = row["base_name"]
      candidates = row["candidates"].split(", ")

      base_candidate_pairs = []
      candidate_candidate_pairs = []


      # Base vs candidate

      for candidate in candidates:

          overlap = (
              entity_to_horses(base)
              .intersection(
                  entity_to_horses(candidate)
              )
          )

          if overlap:
              base_candidate_pairs.append(
                  f"{base} - {candidate}"
              )

      # Candidate vs candidate

      for a, b in combinations(candidates, 2):

          overlap = (
              entity_to_horses(a)
              .intersection(
                  entity_to_horses(b)
              )
          )

          if overlap:
              candidate_candidate_pairs.append(
                  f"{a} - {b}"
              )


      return pd.Series({
          "base_candidate_overlap_pairs": "; ".join(base_candidate_pairs),
          "candidate_candidate_overlap_pairs": "; ".join(candidate_candidate_pairs)
      })

  # Add columns

  entity_overlap_table = (
      final_match_table
      .copy()
  )


  entity_overlap_table[
      [
          "base_candidate_overlap_pairs",
          "candidate_candidate_overlap_pairs"
      ]
  ] = (
      entity_overlap_table
      .apply(find_overlap_pairs, axis=1)
  )

  return entity_overlap_table

def map_overlap(entity, candidate_table, df):

  entity_overlap_table = candidate_table.copy()

  G = nx.Graph()

  for _, row in entity_overlap_table.iterrows():

      pairs = []

      if row["base_candidate_overlap_pairs"]:
          pairs.extend(
              row["base_candidate_overlap_pairs"].split("; ")
          )

      if row["candidate_candidate_overlap_pairs"]:
          pairs.extend(
              row["candidate_candidate_overlap_pairs"].split("; ")
          )


      for pair in pairs:

          entity1, entity2 = pair.split(" - ")

          G.add_edge(entity1, entity2)

  # Count original entity appearances

  entity_counts = (
      df[entity]
      .value_counts()
      .to_dict()
  )

  # Map each connected group to most common entity name

  entity_mapping = {}

  for component in nx.connected_components(G):

      canonical_name = max(
          component,
          key=lambda x: entity_counts.get(x, 0)
      )

      for entity in component:
          entity_mapping[entity] = canonical_name

  return entity_mapping

class MLPDataset(Dataset):
    def __init__(self, X_cat, X_num, y):
        self.X_cat = X_cat
        self.X_num = X_num
        self.y = y

    def __len__(self):
        return len(self.y)

    def __getitem__(self, idx):
        return {
            "cat": self.X_cat[idx],
            "num": self.X_num[idx],
            "y": self.y[idx]
        }

def prepare_data():

    df = pd.read_csv("raceform.csv")

    # Convert features

    df['sp'] = df['sp'].apply(convert_sp)

    df['dist'] = df['dist'].apply(convert_dist)

    #ovr_btn convert to numeric
    df['ovr_btn'] = pd.to_numeric(
        df['ovr_btn'].replace(['-'], np.nan),
        errors='coerce'
    )
    #strip course
    df["course"] = (
        df["course"]
        .str.replace(r"\s*\([^)]*\)", "", regex=True)
        .str.strip()
        .str.lower()
    )

    #rename to avoid conflict with python keywords
    df = df.rename(columns={"class": "race_class"})
    df = df.rename(columns={"type": "race_type"})

    #extract month and year from date
    df['date'] = pd.to_datetime(df['date'])
    df['month'] = df['date'].dt.month
    df['year'] = df['date'].dt.year

    # Converts weight format to pounds
    parts = df["wgt"].str.split("-", expand=True)

    df["wgt"] = (parts[0].astype(float) * 14 + parts[1].astype(float))
    del parts

    cols_to_drop = list(df.columns[df.isna().mean() > 0.5]) +["comment", "num", "rpr", "ts", "prize", "time", "ran", "race_name", "btn"]
    df = df.drop(columns=cols_to_drop)

    #fill blanks with 'MISSING'
    df['sp'] = df['sp'].fillna(df['sp'].median())
    df['draw'] = df['draw'].fillna('MISSING')
    df['draw'] = df['draw'].astype(str)
    df['race_class'] = df['race_class'].fillna('MISSING')
    df['draw'] = df['draw'].fillna('MISSING')
    df['age_band'] = df['age_band'].fillna('MISSING')
    df['going'] = df['going'].fillna('MISSING')
    df['jockey'] = df['jockey'].fillna('MISSING')
    df['trainer'] = df['trainer'].fillna('MISSING')
    df['draw'] = df['draw'].fillna('MISSING')
    df['dam'] = df['dam'].fillna('MISSING')
    df['damsire'] = df['damsire'].fillna('MISSING')
    df['owner'] = df['owner'].fillna('MISSING')

    df['pos_numeric'] = pd.to_numeric(df['pos'], errors='coerce')
    df['finished'] = df['pos_numeric'].notna().astype(int)
    df['pos_numeric'] = df['pos_numeric'].fillna(0)

    df["horse_clean"] = df["horse"].apply(clean_horses_names)
    df["dam_clean"] = df["dam"].apply(clean_horses_names)
    df["damsire_clean"] = df["damsire"].apply(clean_horses_names)
    df["sire_clean"] = df["sire"].apply(clean_horses_names)
    df["jockey_clean"] = df["jockey"].apply(clean_names)
    df["trainer_clean"] = df["trainer"].apply(clean_names)
    df["owner_clean"] = df["owner"].apply(clean_names)

    #mapping horses, dams and damsires to consistent spelling
    horse_mapping = {
        "angea cara fr": "angela cara fr",
        "hardi blue trois aa fr": "hardi blue trois fr",
        "sublime chope fr": "sublime chop fr"
    }
    dam_mapping = {
        "o k angie arg" : "ok angie arg",
        "moonlight shadow gb" : "moon light shadow gb",
        "sound out ire" : "soundout ire",
        "ticker tapei gb" : "ticker tape gb",
        "ascolini aus" : "ascolini nz",
        "nation ii usa" : "nation usa",
        "sun song ii fr" : "sun song fr"
    }
    damsire_mapping = {
        "a p indy": "ap indy",
        "ut*windsor heights" : "windsor heights",
        "ut*mangarose" : "mangarose",
        "almutawakel" : "almutawakeli"
    }
    jockey_mapping = {
        "E Dwan": "Evan Dwan",
        "M J M OSullivan": "Michael OSullivan"
    }

    mask = (
        df["dam_clean"].eq("private jet usa")
        & df["damsire_clean"].isna()
    )
    df.loc[mask, "damsire_clean"] = "smart strike"
    mask = (
        df["horse_clean"].eq("hapi jpn")
        & df["damsire_clean"].isna()
    )
    df.loc[mask, "dam_clean"] = "queen pirates jpn"
    df["damsire_clean"] = df["damsire_clean"].str.rstrip()

    df.loc[
        (df["horse_clean"] == "ectasy usa") &
        (df["race_id"] == 873561),
        "age"
    ] = 3

    df.loc[
        (df["horse_clean"] == "felix felices fr") &
        (df["dam_clean"] == "just eile ire"),
        "horse_clean"
    ] = "felix felices ire"

    df["horse_final"] = df["horse_clean"].replace(horse_mapping)
    df["dam_final"] = df["dam_clean"].replace(dam_mapping)
    df["damsire_final"] = df["damsire_clean"].replace(damsire_mapping)
    df["jockey_clean"] = df["jockey_clean"].replace(jockey_mapping)

    # Names that must keep their titles as separate identities
    keep_titles = {
        "mr a jones",
        "miss a jones",
        "miss m osullivan",
        "ms m osullivan"
    }

    # Restore original titled names for these exceptions
    df.loc[
        df["jockey"].str.lower().isin(keep_titles),
        "jockey_clean"
    ] = df.loc[
        df["jockey"].str.lower().isin(keep_titles),
        "jockey"
    ].str.lower()

    #create dam_id, horse_id, damsire_id, sire_id and jockey_id
    df["dam_id"] = (
        df["dam_final"].str.strip().str.replace(r"\s+", "_", regex=True)
        + "_" +
        df["damsire_clean"].fillna("unknown_dam").str.strip().str.replace(r"\s+", "_", regex=True)
    )
    df["horse_id"] = (
        df["horse_final"].str.strip().str.replace(r"\s+", "_", regex=True)
        + "_" +
        df["dam_id"].fillna("unknown_dam").str.strip().str.replace(r"\s+", "_", regex=True)
    )
    df["damsire_id"] = (
        df["damsire_final"].str.strip().str.replace(r"\s+", "_", regex=True)
    )
    df["sire_id"] = (
        df["sire_clean"].str.strip().str.replace(r"\s+", "_", regex=True)
    )

    df["jockey_id"] = (
        df["jockey_clean"].str.strip().str.replace(r"\s+", "_", regex=True)
    )

    mask = df["horse_clean"].eq("what a whopper")

    df.loc[mask, "horse_id"] = (
        df.loc[mask, "horse_clean"]
        + "_"
        + df.loc[mask, "sire_id"].astype(str)
    )

    del df["horse_clean"]
    del df["dam_clean"]
    del df["damsire_clean"]
    del df["sire_clean"]
    del df["jockey_clean"]

    #create trainer id
    trainer_table = match_table("trainer", df)
    trainer_overlap = overlap("trainer", trainer_table, df)
    trainer_map = map_overlap("trainer", trainer_overlap, df)
    df["trainer_id"] = (
        df["trainer"]
        .replace(trainer_map)
        .str.lower()
        .str.replace(" ", "_")
    )
    #create owener id
    owner_table = match_table("owner", df)
    owner_overlap = overlap("owner", owner_table, df)
    owner_map = map_overlap("owner", owner_overlap, df)
    df["owner_id"] = (
        df["owner"]
        .replace(trainer_map)
        .str.lower()
        .str.replace(" ", "_")
    )

    del trainer_table, trainer_overlap, trainer_map
    del owner_table, owner_overlap, owner_map

    # Form

    #create form for each horse
    df = df.sort_values(['horse_id', 'date'])

    df['horse_ewa_pos'] = (
        df.groupby('horse_id')['pos_numeric']
          .shift()
          .groupby(df['horse_id'])
          .ewm(alpha=0.3, adjust=False)
          .mean()
          .reset_index(level=0, drop=True)
    )
    #ovr_btn?
    df['horse_ewa_btn'] = (
        df.groupby('horse_id')['ovr_btn']
          .shift()
          .groupby(df['horse_id'])
          .ewm(alpha=0.3, adjust=False)
          .mean()
          .reset_index(level=0, drop=True)
    )
    df['horse_ewa_finish_rate'] = (
        df.groupby('horse_id')['finished']
          .shift()
          .groupby(df['horse_id'])
          .ewm(alpha=0.3, adjust=False)
          .mean()
          .reset_index(level=0, drop=True)
    )

    # Create jockey form
    df = df.sort_values(['jockey_id', 'date'])

    df['jockey_ewa_pos'] = (
        df.groupby('jockey_id')['pos_numeric']
          .shift()
          .groupby(df['jockey_id'])
          .ewm(alpha=0.3, adjust=False)
          .mean()
          .reset_index(level=0, drop=True)
    )
    df['jockey_ewa_btn'] = (
        df.groupby('jockey_id')['ovr_btn']
          .shift()
          .groupby(df['jockey_id'])
          .ewm(alpha=0.3, adjust=False)
          .mean()
          .reset_index(level=0, drop=True)
    )
    df['jockey_ewa_finish_rate'] = (
        df.groupby('jockey_id')['finished']
          .shift()
          .groupby(df['jockey_id'])
          .ewm(alpha=0.3, adjust=False)
          .mean()
          .reset_index(level=0, drop=True)
    )

    # Create horse - jockey form
    df = df.sort_values(['horse_id', 'jockey_id', 'date'])

    df['horse_jockey_ewa_pos'] = (
        df.groupby(['horse_id', 'jockey_id'])['pos_numeric']
          .shift()
          .groupby([df['horse_id'], df['jockey_id']])
          .ewm(alpha=0.3, adjust=False)
          .mean()
          .reset_index(level=[0,1], drop=True)
    )
    df['horse_jockey_ewa_btn'] = (
        df.groupby(['horse_id', 'jockey_id'])['ovr_btn']
          .shift()
          .groupby([df['horse_id'], df['jockey_id']])
          .ewm(alpha=0.3, adjust=False)
          .mean()
          .reset_index(level=[0,1], drop=True)
    )
    df['horse_jockey_ewa_finish_rate'] = (
        df.groupby(['horse_id', 'jockey_id'])['finished']
          .shift()
          .groupby([df['horse_id'], df['jockey_id']])
          .ewm(alpha=0.3, adjust=False)
          .mean()
          .reset_index(level=[0,1], drop=True)
    )

    df["horse_form_available"] = df["horse_ewa_pos"].notna().astype(int)
    df["jockey_form_available"] = df["jockey_ewa_pos"].notna().astype(int)
    df["horse_jockey_form_available"] = df["horse_jockey_ewa_pos"].notna().astype(int)

    return df

def prepare_mlp_data(df):

    one_hot_source_cols = [
    "race_class",
    "race_type",
    "sex",
    "going",
    "age_band",
    "month"
    ]
    one_hot_df = pd.get_dummies(
    df[one_hot_source_cols],
    dtype=np.float32
    )


    ignore_cols = ['horse', 'dam', 'sire', 'damsire', 'jockey', 'trainer', 'owner', 'pos', 'date', 'jockey_clean', 'trainer_clean', 'owner_clean', 'horse_clean', 'dam_clean', 'damsire_clean', 'sire_clean','dam_final', 'horse_final', 'damsire_final' , 'draw', 'off', 'or', 'pos_numeric', 'ovr_btn', 'current_age', 'birth_year', 'finished', 'race_id']
    target_col = ['top3']
    cat_cols = ['horse_id', 'dam_id', 'sire_id', 'damsire_id', 'jockey_id', 'trainer_id', 'owner_id', 'course']
    one_hot_cols = one_hot_df.columns.tolist()
    num_cols = [c for c in df.columns if c not in cat_cols + ignore_cols + target_col + one_hot_source_cols]

    # Sort chronologically first
    order = np.argsort(df["date"].to_numpy())

    df["top3"] = (
        (df["pos_numeric"] >= 1) &
        (df["pos_numeric"] <= 3)
    ).astype(float)

    # Create feature sets
    X_cat = df[cat_cols].iloc[order].copy()
    X_num = df[num_cols].iloc[order].copy()
    X_one_hot = one_hot_df.iloc[order].copy()
    y = df[["top3"]].iloc[order].copy()

    n = len(df)

    train_end = int(n * 0.70)
    val_end = int(n * 0.90)

    # Train
    X_cat_train = X_cat.iloc[:train_end].copy()
    X_num_train = X_num.iloc[:train_end].copy()
    X_one_hot_train = X_one_hot.iloc[:train_end].copy()
    y_train = y.iloc[:train_end].copy()


    # Validation
    X_cat_val = X_cat.iloc[train_end:val_end].copy()
    X_num_val = X_num.iloc[train_end:val_end].copy()
    X_one_hot_val = X_one_hot.iloc[train_end:val_end].copy()
    y_val = y.iloc[train_end:val_end].copy()


    # Test
    X_cat_test = X_cat.iloc[val_end:].copy()
    X_num_test = X_num.iloc[val_end:].copy()
    X_one_hot_test = X_one_hot.iloc[val_end:].copy()
    y_test = y.iloc[val_end:].copy()

    X_num_train = X_num_train.fillna(0)
    X_num_val = X_num_val.fillna(0)
    X_num_test = X_num_test.fillna(0)

    X_one_hot_train = X_one_hot_train.fillna(0).values
    X_one_hot_val = X_one_hot_val.fillna(0).values
    X_one_hot_test = X_one_hot_test.fillna(0).values

    scaler = StandardScaler()

    X_num_train = scaler.fit_transform(X_num_train).astype(np.float32)
    X_num_val = scaler.transform(X_num_val).astype(np.float32)
    X_num_test = scaler.transform(X_num_test).astype(np.float32)

    X_num_train = np.concatenate(
        [X_num_train, X_one_hot_train],
        axis=1
    )

    X_num_val = np.concatenate(
        [X_num_val, X_one_hot_val],
        axis=1
    )

    X_num_test = np.concatenate(
        [X_num_test, X_one_hot_test],
        axis=1
    )

    del X_num, X_one_hot, X_one_hot_train, X_one_hot_val, X_one_hot_test

    cat_maps = {}

    for col in cat_cols:

        # Fit mapping only on training data
        labels, uniques = pd.factorize(
            X_cat_train[col]
        )
        cat_maps[col] = uniques

        mapping = {
            value: idx + 1
            for idx, value in enumerate(uniques)
        }

        X_cat_train[col] = labels
        X_cat_val[col] = X_cat_val[col].map(mapping)
        X_cat_test[col] = X_cat_test[col].map(mapping)
        X_cat_val[col] = X_cat_val[col].fillna(0)
        X_cat_test[col] = X_cat_test[col].fillna(0)

    X_cat_train = torch.tensor(
        X_cat_train.values,
        dtype=torch.long
    )

    X_cat_val = torch.tensor(
        X_cat_val.values,
        dtype=torch.long
    )

    X_cat_test = torch.tensor(
        X_cat_test.values,
        dtype=torch.long
    )


    X_num_train = torch.tensor(
        X_num_train,
        dtype=torch.float32
    )

    X_num_val = torch.tensor(
        X_num_val,
        dtype=torch.float32
    )

    X_num_test = torch.tensor(
        X_num_test,
        dtype=torch.float32
    )


    y_train = torch.tensor(
        y_train.values,
        dtype=torch.float32
    )

    y_val = torch.tensor(
        y_val.values,
        dtype=torch.float32
    )

    y_test = torch.tensor(
        y_test.values,
        dtype=torch.float32
    )

    train_dataset = MLPDataset(
    X_cat_train,
    X_num_train,
    y_train
    )

    val_dataset = MLPDataset(
        X_cat_val,
        X_num_val,
        y_val
    )

    test_dataset = MLPDataset(
        X_cat_test,
        X_num_test,
        y_test
    )

    train_loader = DataLoader(
        train_dataset,
        batch_size=1024,
        shuffle=True
    )

    val_loader = DataLoader(
        val_dataset,
        batch_size=1024,
        shuffle=False
    )

    test_loader = DataLoader(
        test_dataset,
        batch_size=1024,
        shuffle=False
    )

    return train_loader, val_loader, test_loader, cat_maps, train_dataset, val_dataset, test_dataset

def prepare_gnn_data(df):

  # Sort data chronologically
  order = np.argsort(df["date"].to_numpy())

  #target
  df["top3"] = (
      (df["pos_numeric"] >= 1) &
      (df["pos_numeric"] <= 3)
  ).astype(float)

  y = df["top3"].to_numpy()[order]
  y = torch.tensor(y, dtype=torch.float32)
  n = len(df)

  #chronological split
  train_end = int(n * 0.70)
  val_end = int(n * 0.90)

  # Runner indices
  train_indices = torch.arange(0, train_end)
  val_indices = torch.arange(train_end, val_end)
  test_indices = torch.arange(val_end, n)

  #create runner_id
  runner_id = np.arange(n)

  form_cols = [
    "horse_jockey_ewa_pos",
    "horse_jockey_ewa_btn",
    "horse_jockey_ewa_finish_rate",
    "jockey_ewa_pos",
    "jockey_ewa_btn",
    "jockey_ewa_finish_rate",
    "horse_ewa_pos",
    "horse_ewa_btn",
    "horse_ewa_finish_rate"
    ]

  race_num_cols = [ "dist", "year"]
  runner_num_cols = ["wgt", 'age', 'sp'] + form_cols
  df[race_num_cols] = df[race_num_cols].astype("float32")
  df[runner_num_cols] = df[runner_num_cols].astype("float32")

  #scale numerical runner columns
  runner_num_data = np.column_stack([
      df[column].to_numpy()[order].astype(np.float32)
      for column in runner_num_cols
  ])

  race_num_data = np.column_stack([
      df[column].to_numpy()[order].astype(np.float32)
      for column in race_num_cols
  ])

  # Scale numerical runner columns
  runner_scaler = StandardScaler()
  runner_scaler.fit(runner_num_data[:train_end])

  runner_num_data = np.nan_to_num(
      runner_scaler.transform(runner_num_data).astype(np.float32),
      nan=0.0
  )

  # Scale numerical race columns
  race_scaler = StandardScaler()
  race_scaler.fit(race_num_data[:train_end])

  race_num_data = np.nan_to_num(
      race_scaler.transform(race_num_data).astype(np.float32),
      nan=0.0
  )


  #one hot encode categories that wont be embedded
  race_df = pd.DataFrame({
      "race_id": df["race_id"].to_numpy()[order],
      "dist": race_num_data[:, 0],
      "year": race_num_data[:, 1],
      "going": df["going"].to_numpy()[order],
      "age_band": df["age_band"].to_numpy()[order],
      "race_type": df["race_type"].to_numpy()[order],
      "race_class": df["race_class"].to_numpy()[order],
      "course": df["course"].to_numpy()[order],
      "month": df["month"].to_numpy()[order]
  }).drop_duplicates("race_id")

  race_df = pd.get_dummies(
      race_df,
      columns=["going", "age_band", "race_type", "race_class", "month"],
      dtype=float
  )
  horse_df = pd.DataFrame({
      "horse_id": df["horse_id"].to_numpy()[order],
      "sex": df["sex"].to_numpy()[order],
      "dam_id": df["dam_id"].to_numpy()[order],
      "damsire_id": df["damsire_id"].to_numpy()[order],
      "sire_id": df["sire_id"].to_numpy()[order]
  }).drop_duplicates("horse_id")

  horse_df = pd.get_dummies(
      horse_df,
      columns=["sex"],
      dtype=float
  )
  runner_df = pd.DataFrame({
      "runner_id": runner_id,
      "wgt": runner_num_data[:, 0],
      "age": runner_num_data[:, 1],
      "sp": runner_num_data[:, 2],
      "horse_jockey_ewa_pos": runner_num_data[:, 3],
      "horse_jockey_ewa_btn": runner_num_data[:, 4],
      "horse_jockey_ewa_finish_rate": runner_num_data[:, 5],
      "jockey_ewa_pos": runner_num_data[:, 6],
      "jockey_ewa_btn": runner_num_data[:, 7],
      "jockey_ewa_finish_rate": runner_num_data[:, 8],
      "horse_ewa_pos": runner_num_data[:, 9],
      "horse_ewa_btn": runner_num_data[:, 10],
      "horse_ewa_finish_rate": runner_num_data[:, 11],
      "horse_form_available": df["horse_form_available"].to_numpy()[order],
      "jockey_form_available": df["jockey_form_available"].to_numpy()[order],
      "horse_jockey_form_available": df["horse_jockey_form_available"].to_numpy()[order]
  }).drop_duplicates("runner_id")

  runner_df = pd.get_dummies(
      runner_df,
      columns=[
          "horse_form_available",
          "jockey_form_available",
          "horse_jockey_form_available"
      ],
      dtype=float
  )
  jockey_df = pd.DataFrame({
      "jockey_id": df["jockey_id"].to_numpy()[order]
  }).drop_duplicates("jockey_id")

  trainer_df = pd.DataFrame({
      "trainer_id": df["trainer_id"].to_numpy()[order]
  }).drop_duplicates("trainer_id")

  owner_df = pd.DataFrame({
      "owner_id": df["owner_id"].to_numpy()[order]
  }).drop_duplicates("owner_id")

  #mappings for categorical features that will be embedded
  course_map = {
      v: i+1 for i, v in enumerate(df["course"].dropna().unique())
  }
  dam_map = {
      v: i+1 for i, v in enumerate(df["dam_id"].dropna().unique())
  }
  sire_map = {
      v: i+1 for i, v in enumerate(df["sire_id"].dropna().unique())
  }
  damsire_map = {
      v: i+1 for i, v in enumerate(df["damsire_id"].dropna().unique())
  }

  race_df["course_idx"] = race_df["course"].map(course_map).fillna(0).astype(int)
  horse_df["dam_idx"] = horse_df["dam_id"].map(dam_map).fillna(0).astype(int)
  horse_df["sire_idx"] = horse_df["sire_id"].map(sire_map).fillna(0).astype(int)
  horse_df["damsire_idx"] = horse_df["damsire_id"].map(damsire_map).fillna(0).astype(int)

  #exclude ids, categories and category indexes
  race_x_cols = [
      c for c in race_df.columns
      if c not in ["race_id", "course", "course_idx"]
  ]
  horse_x_cols = [
      c for c in horse_df.columns
      if c not in ["horse_id", "dam_id", "sire_id", "damsire_id", "dam_idx", "sire_idx", "damsire_idx"]
  ]
  runner_x_cols = [
      c for c in runner_df.columns
      if c not in ["runner_id"]
  ]

  #numerical columns to torch tensors
  race_x = torch.tensor(
      race_df[race_x_cols].values,
      dtype=torch.float32
  )
  horse_x = torch.tensor(
      horse_df[horse_x_cols].values,
      dtype=torch.float32
  )
  runner_x = torch.tensor(
      runner_df[runner_x_cols].values,
      dtype=torch.float32
  )
  jockey_x = torch.ones((len(jockey_df), 1))
  trainer_x = torch.ones((len(trainer_df), 1))
  owner_x = torch.ones((len(owner_df), 1))

  #converting to pytorch tensors
  race_course = torch.tensor(
      race_df["course_idx"].values,
      dtype=torch.long
  )
  horse_dam = torch.tensor(
      horse_df["dam_idx"].values,
      dtype=torch.long
  )
  horse_sire = torch.tensor(
      horse_df["sire_idx"].values,
      dtype=torch.long
  )
  horse_damsire = torch.tensor(
      horse_df["damsire_idx"].values,
      dtype=torch.long
  )

  #mapping from each real entity ID to a consecutive integer index
  race_map = {
      race_id: i
      for i, race_id in enumerate(race_df["race_id"])
  }

  horse_map = {
      horse_id: i
      for i, horse_id in enumerate(horse_df["horse_id"])
  }

  runner_map = {
      runner_id: i
      for i, runner_id in enumerate(runner_df["runner_id"])
  }

  jockey_map = {
      jockey_id: i
      for i, jockey_id in enumerate(jockey_df["jockey_id"])
  }

  trainer_map = {
      trainer_id: i
      for i, trainer_id in enumerate(trainer_df["trainer_id"])
  }

  owner_map = {
      owner_id: i
      for i, owner_id in enumerate(owner_df["owner_id"])
  }

  #Creating edges
  runner_nodes = np.arange(
      n,
      dtype=np.int64
  )


  race_codes = pd.factorize(
      df["race_id"].to_numpy()[order],
      sort=False
  )[0].astype(np.int64)

  horse_codes = pd.factorize(
      df["horse_id"].to_numpy()[order],
      sort=False
  )[0].astype(np.int64)

  jockey_codes = pd.factorize(
      df["jockey_id"].to_numpy()[order],
      sort=False
  )[0].astype(np.int64)

  trainer_codes = pd.factorize(
      df["trainer_id"].to_numpy()[order],
      sort=False
  )[0].astype(np.int64)

  owner_codes = pd.factorize(
      df["owner_id"].to_numpy()[order],
      sort=False
  )[0].astype(np.int64)

  race_to_runner = torch.from_numpy(
      np.vstack([
          race_codes,
          runner_nodes
      ])
  )

  horse_to_runner = torch.from_numpy(
      np.vstack([
          horse_codes,
          runner_nodes
      ])
  )

  jockey_to_runner = torch.from_numpy(
      np.vstack([
          jockey_codes,
          runner_nodes
      ])
  )

  trainer_to_runner = torch.from_numpy(
      np.vstack([
          trainer_codes,
          runner_nodes
      ])
  )

  owner_to_runner = torch.from_numpy(
      np.vstack([
          owner_codes,
          runner_nodes
      ])
  )

  runner_to_horse = horse_to_runner.flip(0)
  runner_to_jockey = jockey_to_runner.flip(0)
  runner_to_trainer = trainer_to_runner.flip(0)
  runner_to_owner = owner_to_runner.flip(0)
  runner_to_race = race_to_runner.flip(0)

  data = HeteroData()
  data["race"].x = race_x
  data["race"].course_idx = race_course
  data["runner"].x = runner_x
  data["horse"].x = horse_x
  data["horse"].dam_idx = horse_dam
  data["horse"].sire_idx = horse_sire
  data["horse"].damsire_idx = horse_damsire
  data["jockey"].x = jockey_x
  data["trainer"].x = trainer_x
  data["owner"].x = owner_x
  data["runner"].y = y

  data["race", "race_to_runner", "runner"].edge_index = race_to_runner
  data["horse", "horse_to_runner", "runner"].edge_index = horse_to_runner
  data["jockey", "jockey_to_runner", "runner"].edge_index = jockey_to_runner
  data["trainer", "trainer_to_runner", "runner"].edge_index = trainer_to_runner
  data["owner", "owner_to_runner", "runner"].edge_index = owner_to_runner
  data["runner", "runner_to_race", "race"].edge_index = runner_to_race
  data["runner", "runner_to_horse", "horse"].edge_index = runner_to_horse
  data["runner", "runner_to_jockey", "jockey"].edge_index = runner_to_jockey
  data["runner", "runner_to_trainer", "trainer"].edge_index = runner_to_trainer
  data["runner", "runner_to_owner", "owner"].edge_index = runner_to_owner

  train_loader = NeighborLoader(
  data,
  input_nodes=("runner", train_indices),
  num_neighbors=[15,15],
  batch_size=512,
  shuffle=True
  )
  val_loader = NeighborLoader(
      data,
      input_nodes=("runner", val_indices),
      num_neighbors=[15,15],
      batch_size=512,
      shuffle=True
  )
  test_loader = NeighborLoader(
      data,
      input_nodes=("runner", test_indices),
      num_neighbors=[15,15],
      batch_size=512,
      shuffle=True
  )

  return data, train_loader, val_loader, test_loader, train_indices, val_indices