# -*- coding: utf-8 -*-
"""GNN_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_Mp3RhfTn4En54Hzk0-u2ayOy1XNozUc
"""

import torch
import torch.nn as nn
import torch.nn.functional as F
from torch_geometric.nn import SAGEConv, HeteroConv

#Defining Model
class HorsePredictionGNN(nn.Module):
  def __init__(self,data, n_horse_features, n_race_features, n_runner_features, n_jockey_features, n_trainer_features, n_owner_features, dropout= 0.2 ):
    super().__init__()
    self.course_emb = nn.Embedding(int(data["race"].course_idx.max()) + 1, 4)
    self.dam_emb = nn.Embedding(int(data["horse"].dam_idx.max()) + 1, 4)
    self.sire_emb = nn.Embedding(int(data["horse"].sire_idx.max()) + 1, 4)
    self.damsire_emb = nn.Embedding(int(data["horse"].damsire_idx.max()) + 1, 4)

    self.horse_lin = nn.Sequential(
          nn.Linear(n_horse_features + 12, 512),
          nn.ReLU(),
          nn.Dropout(dropout),
          nn.Linear(512, 256),
          nn.ReLU(),
          nn.Dropout(dropout),
          nn.Linear(256, 128),
        )
    self.race_lin = nn.Sequential(
          nn.Linear(n_race_features + 4, 512),
          nn.ReLU(),
          nn.Dropout(dropout),
          nn.Linear(512, 256),
          nn.ReLU(),
          nn.Dropout(dropout),
          nn.Linear(256, 128),
        )
    self.runner_lin = nn.Sequential(
          nn.Linear(n_runner_features, 512),
          nn.ReLU(),
          nn.Dropout(dropout),
          nn.Linear(512, 256),
          nn.ReLU(),
          nn.Dropout(dropout),
          nn.Linear(256, 128),
        )
    self.jockey_lin = nn.Sequential(
          nn.Linear(n_jockey_features, 256),
          nn.ReLU(),
          nn.Dropout(dropout),
          nn.Linear(256, 128),
              )
    self.trainer_lin = nn.Sequential(
          nn.Linear(n_trainer_features, 256),
          nn.ReLU(),
          nn.Dropout(dropout),
          nn.Linear(256, 128),
              )
    self.owner_lin = nn.Sequential(
          nn.Linear(n_owner_features, 256),
          nn.ReLU(),
          nn.Dropout(dropout),
          nn.Linear(256, 128),
        )

    self.conv1 = HeteroConv({
    edge_type: SAGEConv((-1, -1), 128)
    for edge_type in data.metadata()[1]
    }, aggr="mean")

    self.conv2 = HeteroConv({
    edge_type: SAGEConv((-1, -1), 128)
    for edge_type in data.metadata()[1]
    }, aggr="mean")

    self.predictor = nn.Linear(128, 1)

  def forward(self, data):

    x_dict = data.x_dict
    edge_index_dict = data.edge_index_dict

    x_dict["race"] = torch.cat([x_dict["race"], self.course_emb(data["race"].course_idx)], dim = 1)
    x_dict["horse"] = torch.cat([x_dict["horse"],
                                 self.dam_emb(data["horse"].dam_idx),
                                 self.sire_emb(data["horse"].sire_idx),
                                 self.damsire_emb(data["horse"].damsire_idx)],
                                dim = 1)
    x_dict["race"] = self.race_lin(x_dict["race"])
    x_dict["horse"] = self.horse_lin(x_dict["horse"])
    x_dict["runner"] = self.runner_lin(x_dict["runner"])
    x_dict["jockey"] = self.jockey_lin(x_dict["jockey"])
    x_dict["trainer"] = self.trainer_lin(x_dict["trainer"])
    x_dict["owner"] = self.owner_lin(x_dict["owner"])

    runner_initial = x_dict["runner"]
    x_dict_conv1 = self.conv1(x_dict, edge_index_dict)
    x_dict = {
          node_type: F.relu(x)
          for node_type, x in x_dict_conv1.items()
      }
    x_dict_conv2 = self.conv2(
        x_dict,
        edge_index_dict
    )

    runner_conv = F.relu(x_dict_conv2["runner"])
    runner_final = runner_conv + runner_initial

    return self.predictor(runner_final)

def process_gnn_batch(batch, device):

    batch = batch.to(device)

    batch_size = batch["runner"].batch_size
    batch_y = batch["runner"].y[:batch_size].unsqueeze(1)

    return batch, batch_y, batch_size