# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/154gar6N8myvfEdPuftT5T9qAhApilfoh
"""

import torch
from GNN_model import HorsePredictionGNN, process_gnn_batch
from train_validate_func import train_and_validate
from torch_geometric.loader import NeighborLoader
from torch.utils.data import DataLoader
import random
from data_prep import prepare_data, prepare_mlp_data, prepare_gnn_data
import numpy as np
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt
import pandas as pd
from MLP_model import HorsePredictionMLP, process_mlp_batch
from evaluation_func import evaluate_model

# Reproducibility
random_seed = 42

random.seed(random_seed)
np.random.seed(random_seed)
torch.manual_seed(random_seed)
torch.cuda.manual_seed_all(random_seed)

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

#prepare datset
#Expected run time: 6 minutes
df = prepare_data()

# Prepare GNN data and data loaders
data, gnn_train_loader, gnn_val_loader, gnn_test_loader, train_indices, val_indices = prepare_gnn_data(df)

# Prepare MLP data and data loaders
mlp_train_loader, mlp_val_loader, mlp_test_loader, cat_maps, train_dataset, val_dataset, test_dataset = prepare_mlp_data(df)

#plot loss and accuracy
def plot_loss_accuracy(train_losses, val_losses):
  plt.figure(figsize=(10, 5))
  epochs = range(1, len(train_losses) + 1)
  plt.plot(epochs, train_losses, label = 'Train Loss', marker = 'o')
  plt.plot(epochs, val_losses, label = 'Validation Loss', marker = 'o')
  plt.title('Training vs Validation Loss')
  plt.xlabel('Epoch')
  plt.xticks(epochs)
  plt.ylabel('Loss')
  plt.legend()
  plt.grid(True)
  plt.show()

#Initialise GNN model
gnn_model_args = {
    "n_horse_features": data["horse"].x.shape[1],
    "n_race_features": data["race"].x.shape[1],
    "n_runner_features": data["runner"].x.shape[1],
    "n_jockey_features": data["jockey"].x.shape[1],
    "n_trainer_features": data["trainer"].x.shape[1],
    "n_owner_features": data["owner"].x.shape[1],
    "data": data
}

gnn_model = HorsePredictionGNN(
    **gnn_model_args,
    dropout=0.2
).to(device)

#Initialise MLP model
mlp_model_args = {
    "n_horse_id": len(cat_maps["horse_id"]) + 1,
    "n_dam_id": len(cat_maps["dam_id"]) + 1,
    "n_sire_id": len(cat_maps["sire_id"]) + 1,
    "n_damsire_id": len(cat_maps["damsire_id"]) + 1,
    "n_jockey_id": len(cat_maps["jockey_id"]) + 1,
    "n_trainer_id": len(cat_maps["trainer_id"]) + 1,
    "n_owner_id": len(cat_maps["owner_id"]) + 1,
    "n_course": len(cat_maps["course"]) + 1,
    "num_features": train_dataset.X_num.shape[1],
    "output_size": train_dataset.y.shape[1]
}
mlp_model = HorsePredictionMLP(
    **mlp_model_args
    dropout=0.3
).to(device)

#Run and plot GNN model
#Expected run time: 3m 20s per epoch
optimizer = torch.optim.Adam(gnn_model.parameters(), lr=0.001)
path = 'best_gnn.pth'
train_losses, val_losses, best_val_auc = train_and_validate(
    gnn_model, gnn_train_loader, gnn_val_loader, optimizer, device, path, process_gnn_batch)
plot_loss_accuracy(train_losses, val_losses)

#Run and plot MLP model
#Expected run time: approx 27s per epoch
optimizer = torch.optim.Adam(mlp_model.parameters(), lr=0.0001)
path = 'best_mlp.pth'
train_losses, val_losses, best_val_auc = train_and_validate(
    mlp_model, mlp_train_loader, mlp_val_loader, optimizer, device, path, process_mlp_batch)
plot_loss_accuracy(train_losses, val_losses)

#Get model weights
gnn_checkpoint = torch.load(
    "best_gnn.pth",
    map_location=device,
    weights_only=False
)

gnn_model.load_state_dict(
    gnn_checkpoint["gnn_model_state_dict"]
)

mlp_checkpoint = torch.load(
    "best_mlp.pth",
    map_location=device,
    weights_only=False
)

mlp_model.load_state_dict(
    mlp_checkpoint["mlp_model_state_dict"]
)

#results
mlp_results = evaluate_model(
    mlp_model,
    mlp_test_loader,
    process_mlp_batch,
    device
)

print(mlp_results)

gnn_results = evaluate_model(
    gnn_model,
    gnn_test_loader,
    process_gnn_batch,
    device
)

print(gnn_results)