# -*- coding: utf-8 -*-
"""MLP_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E93orJqOl6izxsqWQbUMiS8SI2Si1sMN
"""

import torch
import torch.nn as nn
import torch.nn.functional as F

#Defining model
class HorsePredictionMLP(nn.Module):
    def __init__(self, n_horse_id, n_dam_id, n_sire_id, n_damsire_id, n_jockey_id, n_trainer_id, n_owner_id, n_course, num_features, output_size, dropout=0.3):
        super().__init__()
        self.horse_id_emb = nn.Embedding(n_horse_id, 8)
        self.jockey_id_emb = nn.Embedding(n_jockey_id, 8)
        self.trainer_id_emb = nn.Embedding(n_trainer_id, 8)
        self.owner_id_emb = nn.Embedding(n_owner_id, 8)

        self.sire_id_emb = nn.Embedding(n_sire_id, 4)
        self.dam_id_emb = nn.Embedding(n_dam_id, 4)
        self.damsire_id_emb = nn.Embedding(n_damsire_id, 4)
        self.course = nn.Embedding(n_course, 4)

        total_emb = (8 + 8 + 8 + 8 + 4 + 4 + 4 + 4)

        self.fc = nn.Sequential(
          nn.Linear(total_emb + num_features, 512),
          nn.ReLU(),
          nn.Dropout(dropout),
          nn.Linear(512, 256),
          nn.ReLU(),
          nn.Dropout(dropout),
          nn.Linear(256, 128),
          nn.ReLU(),
          nn.Linear(128, output_size)
        )

    def forward(self, batch):

      batch_cat = batch["cat"]
      batch_num = batch["num"]

      horse_id = batch_cat[:, 0]
      dam_id = batch_cat[:, 1]
      sire_id = batch_cat[:, 2]
      damsire_id = batch_cat[:, 3]
      jockey_id = batch_cat[:, 4]
      trainer_id = batch_cat[:, 5]
      owner_id = batch_cat[:, 6]
      course = batch_cat[:, 7]

      emb = torch.cat([
          self.horse_id_emb(horse_id),
          self.dam_id_emb(dam_id),
          self.sire_id_emb(sire_id),
          self.damsire_id_emb(damsire_id),
          self.jockey_id_emb(jockey_id),
          self.trainer_id_emb(trainer_id),
          self.owner_id_emb(owner_id),
          self.course(course)
      ], dim=1)

      x = torch.cat([emb, batch_num], dim=1)

      return self.fc(x)

def process_mlp_batch(batch, device):

    batch["cat"] = batch["cat"].to(device)
    batch["num"] = batch["num"].to(device)
    batch["y"] = batch["y"].to(device)

    batch_y = batch["y"].view(-1, 1)
    batch_size = len(batch_y)

    return batch, batch_y, batch_size