# -*- coding: utf-8 -*-
"""Tables_for_unique_ids.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hKJfSmW6E1hmymqh1A3yoc5IWeaj3kUP
"""

import pandas as pd
import numpy as np
import re
from rapidfuzz import fuzz
from collections import defaultdict, counter
from itertools import combinations
import networkx as nx

df = pd.read_csv("raceform.csv")

(df.isna().mean() * 100).round(4)

cols_to_drop = list(df.columns[df.isna().mean() > 0.5]) +["comment", "num", "rpr", "ts", "prize", "time", "ran", "race_name", "btn" ]
df = df.drop(columns=cols_to_drop)

df['jockey'] = df['jockey'].fillna('MISSING')
df['trainer'] = df['trainer'].fillna('MISSING')
df['dam'] = df['dam'].fillna('MISSING')
df['damsire'] = df['damsire'].fillna('MISSING')
df['owner'] = df['owner'].fillna('MISSING')
df['sire'] = df['damsire'].fillna('MISSING')

df.isna().sum()

#extract month and year from date
df['date'] = pd.to_datetime(df['date'])
df['month'] = df['date'].dt.month
df['year'] = df['date'].dt.year

# Estimate birth year from race age
df["birth_year"] = df["date"].dt.year - df["age"]

# Convert to current age
current_year = pd.Timestamp.today().year
df["current_age"] = current_year - df["birth_year"]

def clean_horses_names(name):
    if pd.isna(name):
        return None

    name = re.sub(r'[()]', '', name)
    name = name.lower().strip()
    name = re.sub(r'\.', '', name)
    name = re.sub(r'\b(i)\b', '', name)
    name = re.sub(r'\s+', ' ', name).strip()

    return name

df["horse_clean"] = df["horse"].apply(clean_horses_names)
df["dam_clean"] = df["dam"].apply(clean_horses_names)
df["damsire_clean"] = df["damsire"].apply(clean_horses_names)
df["sire_clean"] = df["sire"].apply(clean_horses_names)

northern_codes = [
    "ire", "gb", "usa", "fr", "jpn", "ger", "can",
    "ity", "spa", "alg", "tur", "swe", "nor",
    "den", "bel", "pol", "rus", "swi", "gr",
    "cze", "ksa", "bhr", "kor", "uae", "hol", "mor",
    "aut", "qa", "ind", "hun", "jer", "mex", "ukr",
    "slo", "por", "ser", "bul", "cro", "aze", "tun",
]

southern_codes = [ "aus", "nz", "saf", "zim"]
south_american_codes = ["arg", "brz", "chi", "uru", "per", "ven", "ecu"]

# Unique horse names
horse_names = df["horse_clean"].dropna().unique()

# Lookups
age_lookup = df.groupby("horse_clean")["current_age"].first().to_dict()
dam_lookup = df.groupby("horse_clean")["dam_clean"].first().to_dict()
sire_lookup = df.groupby("horse_clean")["sire_clean"].first().to_dict()
sex_lookup = df.groupby("horse_clean")["sex"].first().to_dict()

# Race ID lookup
race_ids_lookup = (
    df.groupby("horse_clean")["race_id"]
      .apply(set)
      .to_dict()
)


# Group by first 2 letters + country suffix
groups = defaultdict(list)

for name in horse_names:
    key = (name[:2].lower(), name.split()[-1])
    groups[key].append(name)


all_similarities = []


for names in groups.values():

    for i in range(len(names)):
        for j in range(i + 1, len(names)):

            horse1 = names[i]
            horse2 = names[j]

            # 1. Length difference
            if abs(len(horse1) - len(horse2)) > 3:
                continue

            # 2. Country suffix
            if horse1.split()[-1] != horse2.split()[-1]:
                continue

            # 3. Sex check
            sex1 = sex_lookup.get(horse1)
            sex2 = sex_lookup.get(horse2)

            if pd.isna(sex1) or pd.isna(sex2):
                continue

            if sex1 != sex2:
                continue

            # 4. Current racing age check
            age1 = age_lookup.get(horse1)
            age2 = age_lookup.get(horse2)

            if pd.isna(age1) or pd.isna(age2):
                continue

            # Extract country suffixes
            code1 = names[i].split()[-1].lower()
            code2 = names[j].split()[-1].lower()

            # If both horses use Northern Hemisphere rules, ages must match exactly
            if code1 in northern_codes and code2 in northern_codes:
                if age1 != age2:
                    continue

            # Otherwise (South American or other Southern Hemisphere), allow a 1-year difference
            else:
                if abs(age1 - age2) > 1:
                    continue

            # 5. Skip if both names appear in the same race
            if race_ids_lookup[horse1].intersection(race_ids_lookup[horse2]):
                continue

            # 6. Parents exist
            dam1 = dam_lookup.get(horse1)
            dam2 = dam_lookup.get(horse2)

            sire1 = sire_lookup.get(horse1)
            sire2 = sire_lookup.get(horse2)

            if pd.isna(dam1) or pd.isna(dam2):
                continue

            if pd.isna(sire1) or pd.isna(sire2):
                continue

            # 7. Parent similarity
            if fuzz.ratio(dam1, dam2) < 85:
                continue

            if fuzz.ratio(sire1, sire2) < 85:
                continue

            # 8. Horse name similarity
            score = fuzz.ratio(horse1, horse2) / 100

            if score >= 0.85:

                all_similarities.append({
                    "horse_1": horse1,
                    "horse_2": horse2,
                    "age_1": age1,
                    "age_2": age2,
                    "similarity": score,
                    "dam_1": dam1,
                    "dam_2": dam2,
                    "sire_1": sire1,
                    "sire_2": sire2
                })


similarity_table = (
    pd.DataFrame(all_similarities)
      .sort_values(["horse_1", "similarity"], ascending=[True, False])
      .reset_index(drop=True)
)

display(similarity_table)

horse_mapping = {
    "angea cara fr": "angela cara fr",
    "hardi blue trois aa fr": "hardi blue trois fr",
    "sublime chope fr": "sublime chop fr"
}
df["horse_final"] = df["horse_clean"].replace(horse_mapping)

# Horses associated with more than one unique dam
horse_multiple_dams = (
    df.groupby("horse_final")["dam_clean"]
      .nunique()
      .loc[lambda x: x > 1]
      .index
)

# Get dams and put them into separate columns
horse_result = (
    df[df["horse_final"].isin(horse_multiple_dams)]
    [["horse_final", "dam_clean"]]
    .drop_duplicates()
    .assign(dam_number=lambda x: x.groupby("horse_final").cumcount() + 1) #yeah change that
    .pivot(index="horse_final", columns="dam_number", values="dam_clean")
    .reset_index()
)

# Rename columns
horse_result.columns = ["horse_final", "dam_1", "dam_2"]

# Separate table of horses in result with current_age variation > 1 year
age_issue_table = (
    df[df["horse_final"].isin(horse_result["horse_final"])]
    .groupby("horse_final")["current_age"]
    .agg(
        min_current_age="min",
        max_current_age="max"
    )
    .assign(age_range=lambda x: x.max_current_age - x.min_current_age)
    .query("age_range > 1")
    .reset_index()
)
age_ok_table = (
    df[df["horse_final"].isin(horse_result["horse_final"])]
    .groupby("horse_final")
    .agg(
        current_ages=("current_age", lambda x: ", ".join(map(str, sorted(x.unique())))),
        age_range=("current_age", lambda x: x.max() - x.min()),
        dams=("dam_clean", lambda x: list(x.dropna().unique()))
    )
    .reset_index()
)

# Keep only horses with age differences of 1 year or less
age_ok_table = age_ok_table[age_ok_table["age_range"] <= 1]

# Split dams into columns
age_ok_table["dam_1"] = age_ok_table["dams"].str[0]
age_ok_table["dam_2"] = age_ok_table["dams"].str[1]

# Keep final format
age_ok_table = age_ok_table[
    ["horse_final", "current_ages", "dam_1", "dam_2"]
]
age_ok_table = age_ok_table.reset_index(drop=True)

print(age_ok_table)

# Get unique sire-dam-damsire combinations
sire_dam_damsire = (
    df[["sire_clean", "damsire_clean", "dam_clean"]]
    .dropna()
    .drop_duplicates()
)

# Group dams by same sire AND same damsire
dam_groups = defaultdict(list)

for sire, damsire, dam in sire_dam_damsire.values:
    dam_groups[(sire, damsire)].append(dam)

# Compare dams only within same sire + damsire group
similar_dams = []

for (sire, damsire), dams in dam_groups.items():

    dams = list(set(dams))

    if len(dams) < 2:
        continue

    for dam1, dam2 in combinations(dams, 2):

        if dam1 == dam2:
            continue

        score = fuzz.ratio(dam1, dam2) / 100

        if score >= 0.9:
            similar_dams.append(
                {
                    "sire": sire,
                    "damsire": damsire,
                    "dam_1": dam1,
                    "dam_2": dam2,
                    "similarity": round(score, 3)
                }
            )

similar_dam_table = pd.DataFrame(similar_dams)

similar_dam_table = similar_dam_table.reset_index(drop=True)

display(similar_dam_table)

# Find horses with multiple current ages
age_conflicts = (
    df.groupby("horse_final")["current_age"]
      .agg(["min", "max", "nunique"])
      .reset_index()
)

# Keep only horses where age difference is more than 1 year
age_conflicts = age_conflicts[
    (age_conflicts["max"] - age_conflicts["min"]) > 1
]

# Add all ages associated with each horse
age_conflicts = (
    age_conflicts
    .merge(
        df.groupby("horse_final")["current_age"]
          .apply(lambda x: ", ".join(map(str, sorted(x.unique()))))
          .reset_index(name="ages"),
        on="horse_final"
    )
)

# Remove horses that already have multiple dams
age_conflicts_no_dam_conflict = (
    age_conflicts[
        ~age_conflicts["horse_final"].isin(horse_multiple_dams)
    ]
)

display(age_conflicts_no_dam_conflict)

# Standard horse ID
df["horse_id"] = df["horse_final"].str.replace(" ", "_")

# Horses requiring dam appended
horse_result_ids = horse_result["horse_final"].unique()

# Append dam name for those horses
df.loc[
    df["horse_final"].isin(horse_result_ids),
    "horse_id"
] = (
    df.loc[df["horse_final"].isin(horse_result_ids), "horse_final"]
    .str.replace(" ", "_")
    + "_"
    + df.loc[df["horse_final"].isin(horse_result_ids), "dam_clean"]
    .str.replace(" ", "_")
)

display(df[["horse_final", "dam_clean", "horse_id"]].drop_duplicates())

# Get each dam and its unique damsires
dam_damsire_pairs = (
    df.groupby("dam_clean")["damsire_clean"]
      .unique()
      .reset_index()
)

# Keep only dams with multiple damsires
dam_damsire_pairs = dam_damsire_pairs[
    dam_damsire_pairs["damsire_clean"].str.len() > 1
]

# Convert damsire combinations into a consistent tuple
dam_damsire_pairs["damsire_combo"] = (
    dam_damsire_pairs["damsire_clean"]
    .apply(lambda x: tuple(sorted(x)))
)

# Group dams by the same damsire combination
damsire_combo_table = (
    dam_damsire_pairs
    .groupby("damsire_combo")["dam_clean"]
    .apply(lambda x: ", ".join(sorted(x)))
    .reset_index(name="dams")
)

display(damsire_combo_table)

pd.set_option('display.max_colwidth', None)

# Dams with multiple damsires
dam_summary = (
    df.groupby('dam_clean')
      .agg(
          damsires=('damsire_clean',
                    lambda x: ', '.join(sorted(pd.unique(x.dropna())))),
          n_damsires=('damsire_clean',
                      lambda x: len(pd.unique(x.dropna()))),
          sires=('sire_clean',
                 lambda x: ', '.join(sorted(pd.unique(x.dropna()))))
      )
      .reset_index()
)

# Keep only dams with more than one damsire
dam_summary = (
    dam_summary[dam_summary['n_damsires'] > 1]
    .drop(columns='n_damsires')
    .sort_values('dam_clean')
    .reset_index(drop=True)
)

display(dam_summary)

# Unique sire sets for each dam + damsire
dam_damsire_sires = (
    df.groupby(['dam_clean', 'damsire_clean'])['sire_clean']
      .apply(lambda x: set(x.dropna()))
      .reset_index(name='sire_set')
)

results = []

# Process one dam at a time
for dam, group in dam_damsire_sires.groupby('dam_clean'):

    # Only dams with multiple damsires
    if len(group) < 2:
        continue

    # Compare each pair of damsires
    for (_, row1), (_, row2) in combinations(group.iterrows(), 2):

        overlap = row1['sire_set'] & row2['sire_set']

        results.append({
            'dam_clean': dam,
            'damsire_1': row1['damsire_clean'],
            'damsire_2': row2['damsire_clean'],
            'overlap_exists': len(overlap) > 0,
            'overlapping_sires': ', '.join(sorted(overlap)) if overlap else ''
        })

overlap_table = pd.DataFrame(results)

# Create a consistent damsire combination
overlap_table["damsire_combo"] = (
    overlap_table[["damsire_1", "damsire_2"]]
    .apply(lambda x: " | ".join(sorted(x)), axis=1)
)

# TRUE: damsire combinations with sire overlap
true_overlap_table = (
    overlap_table[overlap_table["overlap_exists"]]
    .groupby("damsire_combo")["dam_clean"]
    .apply(lambda x: ", ".join(sorted(x.unique())))
    .reset_index(name="dams")
)

# FALSE: damsire combinations without sire overlap
false_overlap_table = (
    overlap_table[~overlap_table["overlap_exists"]]
    .groupby("damsire_combo")["dam_clean"]
    .apply(lambda x: ", ".join(sorted(x.unique())))
    .reset_index(name="dams")
)

# Get damsire combinations that have overlap
true_combos = set(true_overlap_table["damsire_combo"])

# Remove those combinations from false table
false_overlap_table = (
    false_overlap_table[
        ~false_overlap_table["damsire_combo"].isin(true_combos)
    ]
)
display(true_overlap_table)
display(false_overlap_table)

# Get dams from the false overlap cases
false_dams = false_overlap_table["dams"].str.split(", ").explode().unique()

dam_age_table = (
    df[df["dam_clean"].isin(false_dams)]
    .groupby("dam_clean")
    .agg(
        age_range=("current_age", lambda x: f"{x.min()}-{x.max()}"),
        current_ages=("current_age", lambda x: ", ".join(map(str, sorted(x.dropna().unique()))))
    )
    .reset_index()
)

display(dam_age_table)

# Split sire name and country code
sire_parts = (
    df["sire_clean"]
    .dropna()
    .unique()
)

# Group sires by country code
sire_groups = {}

for sire in sire_parts:
    parts = sire.rsplit(" ", 1)
    if len(parts) == 2:
        name, country = parts
        sire_groups.setdefault(country, []).append(sire)

similar_sires = []

# Compare only within the same country code
for country, sires in sire_groups.items():

    for sire1, sire2 in combinations(sires, 2):

        if sire1 == sire2:
            continue

        # Remove country code before similarity check
        name1 = sire1.rsplit(" ", 1)[0]
        name2 = sire2.rsplit(" ", 1)[0]

        score = fuzz.ratio(name1, name2) / 100

        if score >= 0.9:
            similar_sires.append(
                {
                    "sire_1": sire1,
                    "sire_2": sire2,
                    "country": country,
                    "similarity": round(score, 3)
                }
            )

similar_sire_table = pd.DataFrame(similar_sires)

display(similar_sire_table)

def clean_names(name):
  if pd.isna(name):
        return None

  name = name.lower().strip()
  name = re.sub(r"\b(mr|mrs|ms|miss|dr)\b", "", name)
  name = name.replace("'", "")
  name = re.sub(r"[^a-z\s]", " ", name)
  name = " ".join(name.split())

  return name

df["jockey_clean"] = df["jockey"].apply(clean_names)
df["trainer_clean"] = df["trainer"].apply(clean_names)
df["owner_clean"] = df["owner"].apply(clean_names)

# -----------------------------------
# Store original names for display
# -----------------------------------

jockey_display = (
    df[["jockey_clean", "jockey"]]
    .dropna()
    .drop_duplicates()
    .groupby("jockey_clean")["jockey"]
    .apply(list)
    .to_dict()
)


# -----------------------------------
# Unique cleaned jockey names
# -----------------------------------

jockey_names = pd.DataFrame({
    "jockey_clean": df["jockey_clean"].dropna().unique()
})

jockey_names["parts"] = jockey_names["jockey_clean"].str.split()

jockey_names = jockey_names[
    jockey_names["parts"].str.len() >= 2
].copy()

jockey_names["surname"] = jockey_names["parts"].str[-1]



# -----------------------------------
# Group by surname
# -----------------------------------

surname_groups = defaultdict(list)

for name, parts, surname in zip(
    jockey_names["jockey_clean"],
    jockey_names["parts"],
    jockey_names["surname"]
):
    surname_groups[surname].append((name, parts))



# -----------------------------------
# Original matching function
# -----------------------------------

def matches_name(base_parts, candidate_parts):

    # surname must match
    if base_parts[-1] != candidate_parts[-1]:
        return False


    base_first = base_parts[0]
    candidate_first = candidate_parts[0]


    # First name
    if len(base_first) == 1:

        if candidate_first[0] != base_first:
            return False

    else:

        if candidate_first != base_first:
            return False



    # Middle names

    base_middle = base_parts[1:-1]
    candidate_middle = candidate_parts[1:-1]


    for i, middle in enumerate(base_middle):

        if i >= len(candidate_middle):
            return False


        if len(middle) == 1:

            if candidate_middle[i][0] != middle:
                return False

        else:

            if candidate_middle[i] != middle:
                return False


    return True



# -----------------------------------
# Determine whether candidate group
# contains a genuine conflict
# -----------------------------------

def candidate_group_conflict(candidates):

    titles = {"mr", "mrs", "ms", "miss"}


    cleaned = []

    for name in candidates:

        parts = [
            x.lower()
            for x in name.split()
            if x.lower() not in titles
        ]

        cleaned.append(parts)



    # compare all candidate pairs

    for i in range(len(cleaned)):

        for j in range(i + 1, len(cleaned)):

            a = cleaned[i]
            b = cleaned[j]


            # surname conflict
            if a[-1] != b[-1]:
                return True


            first_a = a[0]
            first_b = b[0]


            # Two full first names differ
            if len(first_a) > 1 and len(first_b) > 1:

                if first_a != first_b:
                    return True



            # Middle name comparison

            middle_a = a[1:-1]
            middle_b = b[1:-1]


            if middle_a and middle_b:

                # different number of middle names
                if len(middle_a) != len(middle_b):
                    return True


                for x, y in zip(middle_a, middle_b):

                    # both full
                    if len(x) > 1 and len(y) > 1:

                        if x != y:
                            return True


                    # one initial, one full
                    elif len(x) == 1 and len(y) > 1:

                        if x != y[0]:
                            return True


                    elif len(y) == 1 and len(x) > 1:

                        if y != x[0]:
                            return True


    return False



# -----------------------------------
# Find matches
# -----------------------------------

results = []


for _, row in jockey_names.iterrows():

    base_name = row["jockey_clean"]
    base_parts = row["parts"]
    surname = row["surname"]


    candidates = []


    for candidate_name, candidate_parts in surname_groups[surname]:

        if candidate_name == base_name:
            continue


        if matches_name(base_parts, candidate_parts):

            candidates.append(candidate_name)



    candidates = sorted(set(candidates))



    # -----------------------------------
    # Keep only genuine conflicts
    # -----------------------------------

    if (
        len(candidates) >= 2
        and candidate_group_conflict(candidates)
    ):


        base_display = jockey_display.get(
            base_name,
            [base_name]
        )


        candidate_display = []


        for c in candidates:

            candidate_display.extend(
                jockey_display.get(c, [c])
            )


        candidate_display = sorted(set(candidate_display))


        results.append({

            "base_name": ", ".join(base_display),

            "n_candidates": len(candidate_display),

            "candidates": ", ".join(candidate_display)

        })



# -----------------------------------
# Final table
# -----------------------------------

jockey_match_table = pd.DataFrame(results)

# -----------------------------------
# Gender detection
# -----------------------------------

def get_gender(name):
    name = name.strip().lower()

    if name.startswith("mr "):
        return "male"
    elif name.startswith(("miss ", "ms ", "mrs ")):
        return "female"
    else:
        return "neutral"



# -----------------------------------
# Split function
# -----------------------------------

def split_gender_row(row):

    left_names = list(dict.fromkeys(
        x.strip() for x in row["base_name"].split(", ")
    ))

    right_names = list(dict.fromkeys(
        x.strip() for x in row["candidates"].split(", ")
    ))


    # -----------------------------
    # Group left names
    # -----------------------------

    left_groups = {
        "male": [],
        "female": [],
        "neutral": []
    }

    for name in left_names:
        left_groups[get_gender(name)].append(name)

    left_groups = {
        k: v for k, v in left_groups.items()
        if v
    }


    # -----------------------------
    # Group candidates
    # -----------------------------

    candidate_groups = {
        "male": [],
        "female": [],
        "neutral": []
    }

    for name in right_names:
        candidate_groups[get_gender(name)].append(name)


    output = []


    # ==================================================
    # CASE 1:
    # Left side already has gendered names
    # ==================================================

    left_has_gender = any(
        g in left_groups
        for g in ["male", "female"]
    )


    if left_has_gender:

        # Split existing left genders
        for gender in ["male", "female"]:

            if gender in left_groups:

                keep = (
                    candidate_groups[gender]
                    + candidate_groups["neutral"]
                )

                output.append({
                    "base_name": ", ".join(left_groups[gender]),
                    "n_candidates": len(set(keep)),
                    "candidates": ", ".join(sorted(set(keep)))
                })


        # ------------------------------------------------
        # Add missing conflicting gender candidates
        # ONLY when left side is already gendered
        # ------------------------------------------------

        represented_left = set(left_groups.keys())


        for gender in ["male", "female"]:

            if (
                gender not in represented_left
                and candidate_groups[gender]
            ):

                keep = (
                    candidate_groups[gender]
                    + candidate_groups["neutral"]
                )

                output.append({
                    "base_name": ", ".join(candidate_groups[gender]),
                    "n_candidates": len(set(keep)),
                    "candidates": ", ".join(sorted(set(keep)))
                })



    # ==================================================
    # CASE 2:
    # Left side is neutral
    # ==================================================

    else:

        # Only split neutral names when BOTH genders exist
        if (
            candidate_groups["male"]
            and candidate_groups["female"]
        ):

            for gender in ["male", "female"]:

                keep = (
                    candidate_groups[gender]
                    + candidate_groups["neutral"]
                )

                output.append({
                    "base_name": ", ".join(left_names),
                    "n_candidates": len(set(keep)),
                    "candidates": ", ".join(sorted(set(keep)))
                })

        else:

            output.append({
                "base_name": ", ".join(left_names),
                "n_candidates": len(set(right_names)),
                "candidates": ", ".join(sorted(set(right_names)))
            })


    return output



# -----------------------------------
# Apply to table
# -----------------------------------

jockey_gender_split_table = pd.DataFrame(
    [
        new_row
        for _, row in jockey_match_table.iterrows()
        for new_row in split_gender_row(row)
    ]
)


# -----------------------------------
# Remove duplicate rows
# -----------------------------------

jockey_gender_split_table = (
    jockey_gender_split_table
    .drop_duplicates(
        subset=["base_name", "candidates"]
    )
    .reset_index(drop=True)
)


jockey_gender_split_table["n_candidates"] = (
    jockey_gender_split_table["candidates"]
    .str.split(", ")
    .str.len()
)


# -----------------------------------
# Create lookup: jockey -> set of race_ids
# -----------------------------------

jockey_races = (
    df.groupby("jockey")["race_id"]
      .apply(set)
      .to_dict()
)


# -----------------------------------
# Remove candidates appearing in same race
# -----------------------------------

def remove_same_race_candidates(row):

    base_names = [
        x.strip()
        for x in row["base_name"].split(", ")
    ]

    candidates = [
        x.strip()
        for x in row["candidates"].split(", ")
    ]


    # all races for the base names
    base_race_ids = set()

    for base in base_names:
        base_race_ids.update(
            jockey_races.get(base, set())
        )


    remaining = []

    for candidate in candidates:

        candidate_races = jockey_races.get(
            candidate,
            set()
        )

        # remove if candidate ever appears
        # in the same race as base
        if base_race_ids.intersection(candidate_races):
            continue

        remaining.append(candidate)


    return ", ".join(remaining)



# -----------------------------------
# Apply
# -----------------------------------

jockey_gender_split_table["candidates"] = (
    jockey_gender_split_table
    .apply(remove_same_race_candidates, axis=1)
)


# Remove rows where no candidates remain
jockey_gender_split_table = (
    jockey_gender_split_table[
        jockey_gender_split_table["candidates"] != ""
    ]
    .reset_index(drop=True)
)


# Update count
jockey_gender_split_table["n_candidates"] = (
    jockey_gender_split_table["candidates"]
    .str.split(", ")
    .str.len()
)


# counts from the original dataset
count_lookup = df["jockey"].value_counts().to_dict()

def add_count(name):
    n = count_lookup.get(name, 0)
    return f"{name} ({n})"

# copy the table
jockey_gender_split_table_counts = jockey_gender_split_table.copy()

# add counts to base_name
jockey_gender_split_table_counts["base_name"] = (
    jockey_gender_split_table_counts["base_name"]
    .str.split(", ")
    .apply(lambda names: ", ".join(add_count(n) for n in names))
)

# add counts to candidates
jockey_gender_split_table_counts["candidates"] = (
    jockey_gender_split_table_counts["candidates"]
    .str.split(", ")
    .apply(lambda names: ", ".join(add_count(n) for n in names))
)

display(jockey_gender_split_table_counts)

#Identify where trainers and oweners are referenced by multiple names

# Remove titles from names
def strip_titles(name):

    titles = {"mr", "mrs", "ms", "miss"}

    return [
        x.lower()
        for x in name.split()
        if x.lower() not in titles
    ]

# Match two cleaned names

def matches_name(base_parts, candidate_parts):

    # surname
    if base_parts[-1] != candidate_parts[-1]:
        return False


    # first name
    base_first = base_parts[0]
    candidate_first = candidate_parts[0]


    if len(base_first) == 1:

        if candidate_first[0] != base_first:
            return False

    else:

        if candidate_first != base_first:
            return False



    # middle names

    base_middle = base_parts[1:-1]
    candidate_middle = candidate_parts[1:-1]


    for i, middle in enumerate(base_middle):

        if i >= len(candidate_middle):
            return False


        if len(middle) == 1:

            if candidate_middle[i][0] != middle:
                return False

        else:

            if candidate_middle[i] != middle:
                return False


    return True

# Check whether candidates are genuinely conflicting identities

def candidate_group_conflict(candidates):

    cleaned = [
        strip_titles(name)
        for name in candidates
    ]


    for i in range(len(cleaned)):

        for j in range(i + 1, len(cleaned)):

            a = cleaned[i]
            b = cleaned[j]


            # surname
            if a[-1] != b[-1]:
                return True


            # first name
            if (
                len(a[0]) > 1
                and len(b[0]) > 1
                and a[0] != b[0]
            ):
                return True


            # middle names

            middle_a = a[1:-1]
            middle_b = b[1:-1]


            if middle_a and middle_b:

                if len(middle_a) != len(middle_b):
                    return True


                for x, y in zip(middle_a, middle_b):

                    if len(x) > 1 and len(y) > 1:

                        if x != y:
                            return True


                    elif len(x) == 1 and len(y) > 1:

                        if x != y[0]:
                            return True


                    elif len(y) == 1 and len(x) > 1:

                        if y != x[0]:
                            return True


    return False

def match_table(entity):

  entity_clean = f"{entity}_clean"

  # Store original names for display

  entity_display = (
      df[[entity_clean, entity]]
      .dropna()
      .drop_duplicates()
      .groupby(entity_clean)[entity]
      .apply(list)
      .to_dict()
  )

  # Unique cleaned names

  entity_names = pd.DataFrame({
      entity_clean: df[entity_clean]
      .dropna()
      .unique()
  })


  entity_names["parts"] = (
      entity_names[entity_clean]
      .str.split()
  )


  entity_names = entity_names[
      entity_names["parts"].str.len() >= 2
  ].copy()


  entity_names["surname"] = (
      entity_names["parts"]
      .str[-1]
  )

  # Group by surname

  surname_groups = defaultdict(list)


  for row in entity_names.itertuples(index=False):

      surname_groups[row.surname].append(
          (
              getattr(row, entity_clean),
              row.parts
          )
      )

  # Find possible matches

  results = []


  for row in entity_names.itertuples(index=False):

      base_name = getattr(row, entity_clean)
      base_parts = row.parts
      surname = row.surname


      candidates = []


      for candidate_name, candidate_parts in surname_groups[surname]:

          if candidate_name == base_name:
              continue

          if matches_name(base_parts, candidate_parts):
              candidates.append(candidate_name)



      candidates = sorted(set(candidates))

      # Keep only genuine conflicts

      if (
          len(candidates) >= 2
          and candidate_group_conflict(candidates)
      ):


          base_display = entity_display.get(
              base_name,
              [base_name]
          )


          candidate_display = []

          for candidate in candidates:

              candidate_display.extend(
                  entity_display.get(
                      candidate,
                      [candidate]
                  )
              )

          candidate_display = sorted(
              set(candidate_display)
          )

          results.append({
              "base_name": ", ".join(base_display),
              "n_candidates": len(candidate_display),
              "candidates": ", ".join(candidate_display)

          })

  # Initial ambiguity table

  final_match_table = pd.DataFrame(results)
  return final_match_table

def overlap(entity, final_match_table):

  entity_clean = f"{entity}_clean"

  entity_original_to_clean = (
      df[[entity, entity_clean]]
      .dropna()
      .drop_duplicates()
      .set_index(entity)[entity_clean]
      .to_dict()
  )


  # entity_clean to horse_clean set

  entity_horses = (
      df.dropna(subset=[entity_clean, "horse_id"])
        .groupby(entity_clean)["horse_id"]
        .apply(set)
        .to_dict()
  )

  # entity name to horses

  def entity_to_horses(name):

      clean_name = entity_original_to_clean.get(name)

      if clean_name is None:
          return set()

      return entity_horses.get(clean_name, set())

  # Find overlaps

  def find_overlap_pairs(row):

      base = row["base_name"]
      candidates = row["candidates"].split(", ")

      base_candidate_pairs = []
      candidate_candidate_pairs = []


      # Base vs candidate

      for candidate in candidates:

          overlap = (
              entity_to_horses(base)
              .intersection(
                  entity_to_horses(candidate)
              )
          )

          if overlap:
              base_candidate_pairs.append(
                  f"{base} - {candidate}"
              )

      # Candidate vs candidate

      for a, b in combinations(candidates, 2):

          overlap = (
              entity_to_horses(a)
              .intersection(
                  entity_to_horses(b)
              )
          )

          if overlap:
              candidate_candidate_pairs.append(
                  f"{a} - {b}"
              )


      return pd.Series({
          "base_candidate_overlap_pairs": "; ".join(base_candidate_pairs),
          "candidate_candidate_overlap_pairs": "; ".join(candidate_candidate_pairs)
      })

  # Add columns

  entity_overlap_table = (
      final_match_table
      .copy()
  )


  entity_overlap_table[
      [
          "base_candidate_overlap_pairs",
          "candidate_candidate_overlap_pairs"
      ]
  ] = (
      entity_overlap_table
      .apply(find_overlap_pairs, axis=1)
  )

  return entity_overlap_table

def map_overlap(entity, candidate_table):

  entity_overlap_table = candidate_table.copy()

  G = nx.Graph()

  for _, row in entity_overlap_table.iterrows():

      pairs = []

      if row["base_candidate_overlap_pairs"]:
          pairs.extend(
              row["base_candidate_overlap_pairs"].split("; ")
          )

      if row["candidate_candidate_overlap_pairs"]:
          pairs.extend(
              row["candidate_candidate_overlap_pairs"].split("; ")
          )


      for pair in pairs:

          entity1, entity2 = pair.split(" - ")

          G.add_edge(entity1, entity2)

  # Count original entity appearances

  entity_counts = (
      df[entity]
      .value_counts()
      .to_dict()
  )

  # Map each connected group to most common entity name

  entity_mapping = {}

  for component in nx.connected_components(G):

      canonical_name = max(
          component,
          key=lambda x: entity_counts.get(x, 0)
      )

      for entity in component:
          entity_mapping[entity] = canonical_name

  return entity_mapping

trainer_match_table = match_table("trainer")

trainer_overlap_table = overlap(
    "trainer",
    trainer_match_table
)

display(trainer_overlap_table)

owner_match_table = match_table("owner")

owner_overlap_table = overlap(
    "owner",
    owner_match_table
)

display(owner_overlap_table)