# -*- coding: utf-8 -*-
"""train_validate_func.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15pbmQye9DsHMXPuZcmtT9W609xmMDVxi
"""

import torch
import torch.nn.functional as F
from sklearn.metrics import roc_auc_score

#Training and Validation
def train_and_validate(model, train_loader, val_loader, optimizer, device, path, process_batch):

  train_losses = []
  val_losses = []
  num_epochs = 15
  patience = 5
  epochs_no_improve = 0
  min_val_loss = float('inf')
  best_val_auc = 0.0

  for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0

    for batch in train_loader:

        batch, batch_y, batch_size = process_batch(
                batch,
                device
            )


        optimizer.zero_grad()
        logits = model(batch)
        logits = logits[:batch_size]


        #Using BCE loss
        loss = F.binary_cross_entropy_with_logits(
            logits,
            batch_y
        )

        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    epoch_train_loss = running_loss / len(train_loader)

  #validation

    model.eval()
    running_loss = 0.0
    correct = 0
    total = 0
    val_preds = []
    val_targets = []

    with torch.no_grad():
      for batch in val_loader:

        batch, batch_y, batch_size = process_batch(
                batch,
                device
            )

        optimizer.zero_grad()
        logits = model(batch)
        logits = logits[:batch_size]

        loss = F.binary_cross_entropy_with_logits(
            logits,
            batch_y
        )

        running_loss += loss.item()

        p = torch.sigmoid(logits)

        val_preds.append(p.cpu())
        val_targets.append(batch_y.cpu())

      epoch_val_loss = running_loss / len(val_loader)

      val_preds_array = torch.cat(val_preds).numpy().ravel()
      val_targets_array = torch.cat(val_targets).numpy().ravel()

      val_auc = roc_auc_score(
          val_targets_array,
          val_preds_array
      )

    train_losses.append(epoch_train_loss)
    val_losses.append(epoch_val_loss)

    if val_auc > best_val_auc:
      best_val_auc = val_auc
      if path == 'best_gnn.pth':
          torch.save({
              'gnn_model_state_dict': model.state_dict(),
              'AUC score': best_val_auc
          }, path)
      else:
          torch.save({
              'mlp_model_state_dict': model.state_dict(),
              'AUC score': best_val_auc
          }, path)

    if epoch_val_loss < min_val_loss:
      min_val_loss = epoch_val_loss
      epochs_no_improve = 0

    else:
      epochs_no_improve += 1

    if epochs_no_improve >= patience:
      print(f"Early stopping at epoch {epoch+1}")
      break

    print(f'Epoch {epoch+1}/{num_epochs}| '
          f'Train Loss: {epoch_train_loss:.4f}|'
          f'Val Loss: {epoch_val_loss:.4f}|'
          f"Val AUC: {val_auc:.4f}")

  return train_losses, val_losses, best_val_auc