# -*- coding: utf-8 -*-
"""verification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aQLXnWFG4T-1wf8yOY7TTYpn1YM48tW5
"""

import torch
from GNN_model import HorsePredictionGNN, process_gnn_batch
from torch_geometric.loader import NeighborLoader
from torch.utils.data import DataLoader
import random
from data_prep import prepare_data, prepare_mlp_data, prepare_gnn_data
import numpy as np
from sklearn.metrics import roc_auc_score
import matplotlib.pyplot as plt
import pandas as pd
from MLP_model import HorsePredictionMLP, process_mlp_batch
import torch.nn as nn

device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

df = pd.read_csv("raceform.csv")

df = prepare_data()

data, gnn_train_loader, gnn_val_loader, gnn_test_loader, train_indices, val_indices = prepare_gnn_data(df)

mlp_train_loader, mlp_val_loader, mlp_test_loader, cat_maps, train_dataset, val_dataset, test_dataset = prepare_mlp_data(df)

gnn_model_args = {
    "n_horse_features": data["horse"].x.shape[1],
    "n_race_features": data["race"].x.shape[1],
    "n_runner_features": data["runner"].x.shape[1],
    "n_jockey_features": data["jockey"].x.shape[1],
    "n_trainer_features": data["trainer"].x.shape[1],
    "n_owner_features": data["owner"].x.shape[1],
    "data": data
}

gnn_model = HorsePredictionGNN(
    **gnn_model_args,
    dropout=0.2
).to(device)

mlp_model_args = {
    "n_horse_id": len(cat_maps["horse_id"]) + 1,
    "n_dam_id": len(cat_maps["dam_id"]) + 1,
    "n_sire_id": len(cat_maps["sire_id"]) + 1,
    "n_damsire_id": len(cat_maps["damsire_id"]) + 1,
    "n_jockey_id": len(cat_maps["jockey_id"]) + 1,
    "n_trainer_id": len(cat_maps["trainer_id"]) + 1,
    "n_owner_id": len(cat_maps["owner_id"]) + 1,
    "n_course": len(cat_maps["course"]) + 1,
    "num_features": train_dataset.X_num.shape[1],
    "output_size": train_dataset.y.shape[1]
}
mlp_model = HorsePredictionMLP(
    **mlp_model_args
).to(device)

#MLP verification checks
batch = next(iter(mlp_train_loader))

batch["cat"] = batch["cat"].to(device)
batch["num"] = batch["num"].to(device)
batch["y"] = batch["y"].to(device)
optimizer = torch.optim.Adam(mlp_model.parameters(), lr=0.0001)
mlp_model.eval()

with torch.no_grad():
    output = mlp_model(batch)

print("Output shape:", output.shape)
print("Expected shape:", (batch["num"].shape[0], 1))


criterion = nn.BCEWithLogitsLoss()
mlp_model.train()

optimizer.zero_grad()

output = mlp_model(batch)

loss = criterion(
    output,
    batch["y"].float()
)

loss.backward()

print("Loss:", loss.item())
print("Loss is finite:", torch.isfinite(loss).item())

gradient_values = [
    parameter.grad.abs().sum().item()
    for parameter in mlp_model.parameters()
    if parameter.grad is not None
]

print("Total gradient:", sum(gradient_values))

parameter_before = next(mlp_model.parameters()).detach().clone()

optimizer.step()

parameter_after = next(mlp_model.parameters()).detach().clone()

print(
    "Parameter updated:",
    not torch.equal(parameter_before, parameter_after)
)

#GNN verification checks
batch = next(iter(gnn_train_loader))

batch = batch.to(device)

optimizer = torch.optim.Adam(gnn_model.parameters(), lr=0.001)

gnn_model.eval()

with torch.no_grad():

    output = gnn_model(batch)

print("Output shape:", output.shape)

print("Expected shape:", (batch["runner"].x.shape[0], 1))


criterion = nn.BCEWithLogitsLoss()

gnn_model.train()

optimizer.zero_grad()

output = gnn_model(batch)

batch_size = batch["runner"].batch_size

output = output[:batch_size]

target = batch["runner"].y[:batch_size].unsqueeze(1)

loss = criterion(
    output,
    target
)

loss.backward()

print("Loss:", loss.item())

print("Loss is finite:", torch.isfinite(loss).item())

gradient_values = [
    parameter.grad.abs().sum().item()
    for parameter in gnn_model.parameters()
    if parameter.grad is not None
]

print("Total gradient:", sum(gradient_values))

parameter_before = next(gnn_model.parameters()).detach().clone()

optimizer.step()

parameter_after = next(gnn_model.parameters()).detach().clone()

print(
    "Parameter updated:",
    not torch.equal(parameter_before, parameter_after)
)